name: Metrics
on:
  schedule:
    - cron: "30 16 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: CNife
          template: classic
          base: header, activity, community, repositories, metadata
          config_animated: yes
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_stars: yes
          plugin_stars_limit: 5
